### ISSUE TITLE
Add default English?

### ISSUE THREAD

**Issue by Tom3kk** [SharpnelXu/FGOSimulator#2]
The app seems to have english built in, the translation file literally has english word = *chinese translation*, so the app coming without an english translation to switch to by default is really odd...

**Comment by SharpnelXu** [comment]
Yeah I was too lazy......

However, this simulator has already been incorporated into Chaldea, so no longer maintained.

You can use the incorporated Laplace Simulator with [Chaldea](https://github.com/chaldea-center/chaldea)：https://docs.chaldea.center/
